version: "3.1"
services:
   postgres: 
                image: postgres:11-alpine
                restart: always
                environment:
                        POSTGRES_PASSWORD: actix
                        POSTGRES_USER: actix
                        POSTGRES_DB: actix
                ports:
                   - 5432:5432
