name: "Combine Dependabot PRs"
on:
  workflow_call:
    inputs:
      branches:
        description: 'Comma separate string of PRs to combine'
        required: false
        type: string

jobs:
  combine-prs:
    runs-on: ubuntu-latest
    steps:
      - uses: gita-codaio/batch-dependabot@main
        with:
          branchPrefix: "dependabot"
          mustBeGreen: true
          combineBranchName: "combined-prs"
          ignoreLabel: "nocombine"
          baseBranch: "master"
          openPR: true
          allowSkipped: false
