name: "Combine Dependabot PRs"
on:
  workflow_call:
    inputs:
      branches:
        description: 'Comma separate string of PRs to combine'
        required: false
        type: string
  workflow_dispatch:

jobs:
  combine-prs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2.3.3
        with:
           persist-credentials: false

      - uses: gita-codaio/batch-dependabot@master
        with:
          branchPrefix: "dependabot"
          mustBeGreen: true
          combineBranchName: "combined-prs"
          ignoreLabel: "nocombine"
          baseBranch: "main"
          openPR: true
          allowSkipped: false
